### PR TITLE
Header links, Appendable and immutable options 

### PR DESCRIPTION
**Pull request by charleso**
Sorry, a grab-bag of changes, not really related.

Not 100% sure about the header-link change. It's definitely something that is used (ie see jQuery README file). However, there were no tests for those lines of code that I removed so I don't know what I may have broken.

I've used Appendable, well, just because. Now consumers can pass Writers for streaming.

Finally, creating a custom ProcessingOptions was a pain, so I tweaked it slightly, I hope you don't mind.

As some background. Currently I'm using Pegdown for a project at work, but this seems more suitable for our purposes - it's faster and allows streaming which is always a good sign.

### CODE REVIEW

**Comment by sangupta** [comment]
Hi @charleso - sorry but for some reason I missed the notification to the pull request. I will take a look at it tomorrow and merge after testing.

Sorry again - Sandeep.

**Comment by charleso** [comment]
No worries. It's not urgent, just me tinkering. :)

**Comment by charleso** [comment]
I'd forgotten about this. I hope it helps. :)

**Comment by sangupta** [comment]
Hi charleso - even I had forgotten about this one - it surely helps. Am
gonna add more tests and a features to it in the next few weeks.

Thanks for the contributions. Regards!

Keep Walking,
~ Sandeep

**Pull request merged**
